# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/RestSharpExample"
    schedule:
      interval: "monthly" # or daily, monthly
    open-pull-requests-limit: 5