name: GHA test with docker

on:
  workflow_dispatch:
  push:
    paths:
      - 'DockerGithubActionsSimpleExample/**'

env:
  TEST_TAG: rbrych126/gha-test:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: rbrych126/gha-test
          tags: |
            type=raw,value=latest
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          file: ./DockerGithubActionsSimpleExample/Dockerfile
          context: ./DockerGithubActionsSimpleExample
          tags: ${{ env.TEST_TAG }}

      - name: Inspect image
        run: |
          docker images

      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./DockerGithubActionsSimpleExample/Dockerfile
          context: ./DockerGithubActionsSimpleExample
          push: true
          tags: ${{ steps.meta.outputs.tags }}