name: Job Output Test Extended

on:
  workflow_dispatch:

jobs:
  set-output-correctly:
    runs-on: ubuntu-latest
    outputs:
      correct_version: ${{ steps.setver.outputs.version }}
    steps:
      - id: setver
        run: echo "version=1.2.3" >> $GITHUB_OUTPUT

  set-output-via-env-job-level:
    runs-on: ubuntu-latest
    env:
      version: 9.9.9
    outputs:
      job_env_version: ${{ env.version }}
    steps:
      - run: echo "Job-level env version is ${{ env.version }}"

  set-output-via-env-step-level:
    runs-on: ubuntu-latest
    outputs:
      step_env_version: ${{ env.version }}
    steps:
      - name: Set env variable via GITHUB_ENV
        run: echo "version=7.7.7" >> $GITHUB_ENV
      - run: echo "Step-level env version is ${{ env.version }}"

  compare:
    needs: [set-output-correctly, set-output-via-env-job-level, set-output-via-env-step-level]
    runs-on: ubuntu-latest
    steps:
      - name: Compare outputs
        run: |
          echo "✅ Correct (step output): ${{ needs.set-output-correctly.outputs.correct_version }}"
          echo "✅ Job-level env:          ${{ needs.set-output-via-env-job-level.outputs.job_env_version }}"
          echo "❌ Step-level env:         '${{ needs.set-output-via-env-step-level.outputs.step_env_version }}' (expected empty)"